apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: togather-online-tls
spec:
  secretName: togather-online
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: togather.online
  dnsNames:
    - togather.online
    - www.togather.online
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - togather.online
          - www.togather.online
