apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prd
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 'kohkimkhang@yahoo.com'
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}
