apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: kyrie541/togather-server
          ports:
            - containerPort: 8081
          env:
            - name: MONGODB_URL
              value: mongodb://mongodb-cluster-ip-service/togather
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secretkey
                  key: SECRET_KEY
