FROM node:alpine

WORKDIR '/app'

COPY ./package.json ./
COPY ./package-lock.json ./

RUN rm -rf node_modules

RUN apk add --no-cache make gcc g++ python && \
  npm install --silent && \
  apk del make gcc g++ python

COPY . .

CMD ["npm", "run", "dev"]
