FROM node:alpine

WORKDIR '/app'

COPY ./package.json ./

RUN apk add --no-cache make gcc g++ python && \
  npm install --production --silent && \
  apk del make gcc g++ python

COPY . .

CMD ["npm", "run", "dev"]
